/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package comart.tools.jdbgen.ui;

import comart.utils.I18n;
import comart.utils.UIUtils;
import java.awt.Frame;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import javax.swing.SwingUtilities;
import lombok.extern.slf4j.Slf4j;

/**
 * acknowledgements dialog, reachable from the about dialog. The dialog shows
 * the read only content of the bundled <code>/acknowledgements.txt</code>
 * resource, which lists the third party works used by the application. A
 * single shared instance is kept and reused.
 *
 * @author comart
 */
@Slf4j
public class Acknowledgements extends javax.swing.JDialog {

    /** the shared dialog instance, created on the first call of
     * <code>getInstance(Frame)</code>. */
    private static Acknowledgements INSTANCE = null;
    /**
     * return the shared acknowledgements dialog. The dialog is created as a
     * modal dialog of <code>parent</code> and registered for look and feel
     * updates on the first call, later calls reuse that instance regardless of
     * <code>parent</code>. The application icon and the component tree are
     * refreshed on every call.
     *
     * @param parent
     *            frame the dialog is created for, used on the first call only.
     * @return the shared <code>Acknowledgements</code> instance.
     */
    public static synchronized Acknowledgements getInstance(Frame parent) {
        if (INSTANCE == null) {
            INSTANCE = new Acknowledgements(parent, true);
            UIUtils.registerFrame(INSTANCE);
        }
        UIUtils.setApplicationIcon(INSTANCE);

        INSTANCE.updateComponents();
        return INSTANCE;
    }
    
    /**
     * reapply the current look and feel to the whole dialog. Called after a
     * theme or font change so that the already created dialog is redrawn with
     * the new settings.
     */
    public void updateComponents() {
        SwingUtilities.updateComponentTreeUI(this);
    }
    
    /**
     * Creates new form Acknowledgements
     * <p>
     * The dialog is centered on <code>parent</code> and the bundled
     * <code>/acknowledgements.txt</code> resource is read as UTF-8 into the
     * read only text area, an unreadable resource is logged and leaves the
     * text area empty.
     *
     * @param parent
     *            frame the dialog belongs to and is centered on.
     * @param modal
     *            <code>true</code> to create a modal dialog.
     */
    private Acknowledgements(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(parent);
        
        StringBuilder sb = new StringBuilder();
        
        try (InputStream is = Acknowledgements.class.getResourceAsStream("/acknowledgements.txt");
            InputStreamReader rd = new InputStreamReader(is, StandardCharsets.UTF_8)) {
            
            int c;
            while ((c = rd.read()) >= 0) {
                sb.append((char)c);
            }
        } catch (Exception e) {
            log.error("cannot read acknowledges.", e);
        }
        txtContents.setText(sb.toString());
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContents = new javax.swing.JTextArea();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel1.setText(I18n.t("acknowledgements.jLabel1.text"));

        txtContents.setEditable(false);
        txtContents.setColumns(20);
        txtContents.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        txtContents.setRows(5);
        jScrollPane1.setViewportView(txtContents);

        btnOk.setText(I18n.t("acknowledgements.btnOk.text"));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** hide the dialog when the ok button is pressed. */
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * stand alone entry point which shows this dialog on its own, used to
     * preview the form during development. The Nimbus look and feel is
     * selected when available and the virtual machine is terminated once the
     * dialog is closed.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acknowledgements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acknowledgements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acknowledgements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acknowledgements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Acknowledgements dialog = new Acknowledgements(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtContents;
    // End of variables declaration//GEN-END:variables
}
